import models_dir.segmentation_model as segmentation
import models_dir.identification_model as identification_model
import utils_dir.visualization as visualization
import models_dir.text_extraction_model as text_extraction_model
import models_dir.summarization_model as summarization_model
import utils_dir.data_mapping as data_mapping


segmentation.image_segmentation()
identification_model.identify_object()
text_extraction_model.extract_text_main()
summarization_model.generate_summary()
data_mapping.generate_final_mapping()
visualization.final_output()